scheduler:
  evaluationInterval: PT1S

worker:
  connections:
    - hostname: localhost
      port: 28282

workflows:
  workflows:
    - id: literal-workflow
      name: this is literal workflow
      entryPoint:
        trigger:
          kind: com.github.lavenderses.work.domain.model.trigger.DependingTasksCompletedTrigger
          metadata: {}
        follows:
          - job-1
          - job-3
      jobs:
        - id: job-1
          name: echo 1
          kind: com.github.lavenderses.work.domain.model.job.EchoJob
          follows:
            - job-2
          retry: 0
          trigger:
            kind: com.github.lavenderses.work.domain.model.trigger.DependingTasksCompletedTrigger
            metadata: {}
          metadata: {}

        - id: job-2
          name: echo 2
          kind: com.github.lavenderses.work.domain.model.job.EchoJob
          follows: []
          retry: 0
          trigger:
            kind: com.github.lavenderses.work.domain.model.trigger.DependingTasksCompletedTrigger
            metadata: {}
          metadata: {}

        - id: job-3
          name: echo 3
          kind: com.github.lavenderses.work.domain.model.job.EchoJob
          follows:
            - job-4
          retry: 0
          trigger:
            kind: com.github.lavenderses.work.domain.model.trigger.DependingTasksCompletedTrigger
            metadata: {}
          metadata: {}

        - id: job-4
          name: echo 4
          kind: com.github.lavenderses.work.domain.model.job.EchoJob
          follows: []
          retry: 0
          trigger:
            kind: com.github.lavenderses.work.domain.model.trigger.DependingTasksCompletedTrigger
            metadata: {}
          metadata: {}

  imports:
    - templates/echo.yaml
